swagger: '2.0'

info:
  title: "Discord_structure_api"
  version: "1.0"

basePath: /v1.0

paths:
  /Structure/:
    post:
      responses:
        200:
          description: Ok
          
        201:
          description: Created
          
      
      parameters:
        - in: body
          name: serv_structure
          description: return server's structure
          required: true
          schema:
            type: "string"
            
definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int64
      serv_structure: { type: object }


